USE [master]
GO

/****** Object:  Database [Xilion]    Script Date: 5/8/2019 9:24:43 PM ******/
CREATE DATABASE [Xilion]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Xilion', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Xilion.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Xilion_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Xilion_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Xilion] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Xilion].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Xilion] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Xilion] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Xilion] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Xilion] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Xilion] SET ARITHABORT OFF 
GO

ALTER DATABASE [Xilion] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Xilion] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Xilion] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Xilion] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Xilion] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Xilion] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Xilion] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Xilion] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Xilion] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Xilion] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Xilion] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Xilion] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Xilion] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Xilion] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Xilion] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Xilion] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Xilion] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Xilion] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Xilion] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Xilion] SET  MULTI_USER 
GO

ALTER DATABASE [Xilion] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Xilion] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Xilion] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Xilion] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Xilion] SET  READ_WRITE 
GO


